### ISSUE TITLE
Python wrapper set_db_locs TypeError

### ISSUE THREAD

**Issue by wlambooy** [samuelngsh/simanneal-sidb#1]
I am trying to use SimAnneal through the Python wrapper provided in this repository. However, when I try to run the code in the provided example, I run into an error at the `set_db_locs` call. See the full stack trace included below. I tried both Python 3.11 and 3.8.

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/d/Willem/Stack/_RU/_Master/SEM3/Internship/Python/simanneal-sidb/_skbuild/linux-x86_64-3.8/cmake-install/pysimanneal/simanneal.py", line 797, in set_db_locs
    self.setDBLocs(dbs)
  File "/mnt/d/Willem/Stack/_RU/_Master/SEM3/Internship/Python/simanneal-sidb/_skbuild/linux-x86_64-3.8/cmake-install/pysimanneal/simanneal.py", line 751, in setDBLocs
    return _simanneal.SimParams_setDBLocs(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Wrong number or type of arguments for overloaded function 'SimParams_setDBLocs'.
  Possible C/C++ prototypes are:
    phys::SimParams::setDBLocs(std::vector< phys::EuclCoord,std::allocator< phys::EuclCoord > > const &)
    phys::SimParams::setDBLocs(std::vector< phys::LatCoord,std::allocator< phys::LatCoord > > const &)

**Comment by wlambooy** [comment]
I found the bug and created a PR, closing issue.
